"""
Class 6 Intro Video Generator
Produces: content/assets/videos/class-06-intro-charon.mp4
Runtime: ~75 seconds, 1280×720, narrated slideshow

Uses:
- Google Cloud TTS (en-US-Chirp3-HD-Charon) for narration
- moviepy + imageio_ffmpeg
- Class 6 scene images generated by generate_class06_images.py

Run: source .env && .venv/bin/python scripts/generate_class06_video.py
"""

import os
from pathlib import Path

# ── Load .env ────────────────────────────────────────────────────────────────
env_path = Path(__file__).parent.parent / ".env"
if env_path.exists():
    for line in env_path.read_text().splitlines():
        if "=" in line and not line.startswith("#"):
            k, v = line.split("=", 1)
            os.environ.setdefault(k.strip(), v.strip())

# ── Paths ────────────────────────────────────────────────────────────────────
ROOT       = Path(__file__).parent.parent
SCENES_DIR = ROOT / "content" / "assets" / "scenes"
VERSION_SUFFIX = "-charon"
TTS_LANGUAGE_CODE = "en-US"
TTS_VOICE = "en-US-Chirp3-HD-Charon"
TTS_SPEAKING_RATE = 1.0
AUDIO_DIR  = ROOT / "content" / "assets" / "videos" / f"audio_tmp_c06{VERSION_SUFFIX}"
VIDEO_OUT  = ROOT / "content" / "assets" / "videos" / f"class-06-intro{VERSION_SUFFIX}.mp4"

AUDIO_DIR.mkdir(parents=True, exist_ok=True)
VIDEO_OUT.parent.mkdir(parents=True, exist_ok=True)

# ── Script: 8 scenes, ~75 seconds total ─────────────────────────────────────
# (image_filename, narration_text, duration_hint_seconds)
SCENES = [
    (
        "img-c6-01-computer-learning.jpg",
        "Welcome to Class 6 AI — with Mitra AI Life. "
        "This is your very first lesson about Artificial Intelligence. "
        "No coding. No maths. Just understanding how AI works and how to use it wisely.",
        9,
    ),
    (
        "img-c6-02-student-checking.jpg",
        "Meet Anu — an 11-year-old student from Vijayawada. "
        "One day, YouTube recommended a video she never searched for. "
        "She asked — how did YouTube know I would like this? "
        "The answer is Artificial Intelligence.",
        10,
    ),
    (
        "img-c6-01-computer-learning.jpg",
        "AI stands for Artificial Intelligence. "
        "Artificial means made by humans. "
        "Intelligence means the ability to learn and solve problems. "
        "Put them together — AI is a computer program that learns from examples and gives useful answers.",
        10,
    ),
    (
        "img-c6-03-student-ai-tablet.jpg",
        "AI is already around you every day. "
        "YouTube and Reels recommend videos you like. "
        "Google Maps finds the fastest road. "
        "Your phone camera makes your photos look better. "
        "All of that is AI — working quietly in the background.",
        10,
    ),
    (
        "img-c6-02-student-checking.jpg",
        "AI is a powerful helper — but it is not perfect. "
        "It can give wrong answers. It does not know your life. "
        "It cannot replace your teacher. "
        "Always check what AI says against your textbook or a trusted adult.",
        9,
    ),
    (
        "img-c6-03-student-ai-tablet.jpg",
        "Here are your safety rules. "
        "Never share your home address, phone number, or school name with AI. "
        "Never copy AI answers into your notebook. "
        "Always write in your own words after reading the AI answer. "
        "Be honest with your teachers about using AI.",
        10,
    ),
    (
        "img-c6-02-student-checking.jpg",
        "Anu used AI the right way. "
        "She asked AI to explain photosynthesis in simple words. "
        "She read the answer, understood it, and wrote it in her own notebook. "
        "That is the smart student way to use AI.",
        9,
    ),
    (
        "img-c6-01-computer-learning.jpg",
        "In this lesson you will read 5 sections, answer a quick quiz, "
        "and complete a simple worksheet. "
        "Everything is free. No sign-in needed. "
        "Let us begin — and discover AI together!",
        8,
    ),
]

# ── Step 1: TTS audio ────────────────────────────────────────────────────────
print("Step 1: Generating TTS narration audio...")
audio_files = []
from google.cloud import texttospeech

client = texttospeech.TextToSpeechClient()

for i, (img, text, _) in enumerate(SCENES, start=1):
    audio_path = AUDIO_DIR / f"scene-{i:02d}.mp3"
    if audio_path.exists():
        print(f"  [SKIP] Scene {i} audio already exists")
    else:
        print(f"  [{i}/{len(SCENES)}] TTS: {text[:60]}...")
        response = client.synthesize_speech(
            input=texttospeech.SynthesisInput(text=text),
            voice=texttospeech.VoiceSelectionParams(language_code=TTS_LANGUAGE_CODE, name=TTS_VOICE),
            audio_config=texttospeech.AudioConfig(
                audio_encoding=texttospeech.AudioEncoding.MP3,
                speaking_rate=TTS_SPEAKING_RATE,
            ),
            timeout=45,
        )
        audio_path.write_bytes(response.audio_content)
        print(f"    Saved: {audio_path.name}")

    audio_files.append(audio_path)

print(f"  Audio ready: {len(audio_files)} files\n")

# ── Step 2: Build video ──────────────────────────────────────────────────────
print("Step 2: Building video...")

import imageio_ffmpeg
ffmpeg_bin = imageio_ffmpeg.get_ffmpeg_exe()
os.environ["IMAGEIO_FFMPEG_EXE"] = ffmpeg_bin
print(f"  Using ffmpeg: {ffmpeg_bin}")

from moviepy import (
    ImageClip,
    AudioFileClip,
    concatenate_videoclips,
)
from PIL import Image, ImageDraw
import numpy as np

VIDEO_W, VIDEO_H = 1280, 720
FPS = 24


def make_scene_clip(img_path: Path, audio_path: Path):
    audio = AudioFileClip(str(audio_path))
    duration = audio.duration + 0.4

    img = Image.open(img_path).convert("RGB")
    img_w, img_h = img.size
    scale = max(VIDEO_W / img_w, VIDEO_H / img_h)
    new_w, new_h = int(img_w * scale), int(img_h * scale)
    img = img.resize((new_w, new_h), Image.LANCZOS)
    left = (new_w - VIDEO_W) // 2
    top  = (new_h - VIDEO_H) // 2
    img  = img.crop((left, top, left + VIDEO_W, top + VIDEO_H))

    # Bottom gradient overlay
    gradient = Image.new("RGBA", (VIDEO_W, VIDEO_H), (0, 0, 0, 0))
    draw = ImageDraw.Draw(gradient)
    for y in range(VIDEO_H // 2, VIDEO_H):
        alpha = int(180 * ((y - VIDEO_H // 2) / (VIDEO_H // 2)))
        draw.line([(0, y), (VIDEO_W, y)], fill=(0, 0, 0, alpha))
    img_rgba = img.convert("RGBA")
    img_rgba.paste(gradient, (0, 0), gradient)
    frame = np.array(img_rgba.convert("RGB"))

    clip = ImageClip(frame, duration=duration)

    # Ken Burns zoom
    def zoom_frame(get_frame, t):
        f = get_frame(t)
        s = 1.0 + 0.04 * (t / duration)
        h, w = f.shape[:2]
        nw, nh = int(w * s), int(h * s)
        img2 = Image.fromarray(f).resize((nw, nh), Image.LANCZOS)
        ox, oy = (nw - w) // 2, (nh - h) // 2
        return np.array(img2.crop((ox, oy, ox + w, oy + h)))

    clip = clip.transform(zoom_frame, apply_to="video")
    clip = clip.with_audio(audio)
    return clip


clips = []
for i, (img_name, narr_text, _) in enumerate(SCENES, start=1):
    img_path   = SCENES_DIR / img_name
    audio_path = audio_files[i - 1]
    print(f"  [{i}/{len(SCENES)}] Compositing: {img_name}")
    clips.append(make_scene_clip(img_path, audio_path))

print("\nStep 3: Concatenating clips and writing video...")
final = concatenate_videoclips(clips, method="compose")

final.write_videofile(
    str(VIDEO_OUT),
    fps=FPS,
    codec="libx264",
    audio_codec="aac",
    temp_audiofile=str(AUDIO_DIR / "final_audio.m4a"),
    remove_temp=True,
    logger="bar",
)

print(f"\nDone! Video saved to: {VIDEO_OUT}")
print(f"Total duration: {sum(c.duration for c in clips):.1f} seconds")
print(f"File size: {VIDEO_OUT.stat().st_size / 1024 / 1024:.1f} MB")
